version: '3.8'

services:
  web:
    image: nginx:latest
    container_name: ginx_web_prac
    ports:
      - "80:80"
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always

  gitea:
    image: gitea/gitea:latest
    container_name: gitea_server_prac
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__server__DOMAIN=localhost
      - GITEA__server__ROOT_URL=http://localhost:3000/
      - GITEA__security__INSTALL_LOCK=true
      - GITEA__database__DB_TYPE=sqlite3
    volumes:
      - ./gitea:/data
    ports:
      - "3001:3000"   # Web access
      - "2223:22"     # SSH access
    restart: unless-stopped

  sonarqube:
      image: sonarqube:latest
      container_name: sonarqube_prac
      ports:
        - "9000:9000"
      environment:
        - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
      volumes:
        - sonarqube_data:/opt/sonarqube/data
        - sonarqube_extensions:/opt/sonarqube/extensions
        - sonarqube_logs:/opt/sonarqube/logs

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs: