name: CI Workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # ---------- 1. UI Tests with Selenium ---------
  ui-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start Flask server
        run: |
          export FLASK_APP=app.py
          nohup flask run --host=127.0.0.1 --port=5000 > flask.log 2>&1 &
          sleep 5


  # ---------- 2. Dependency Vulnerability Check (pip-audit) -----------
  pip-audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install pip-audit and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pip-audit -r requirements.txt

      - name: Run pip-audit
        run: pip-audit

  # ---------- 3. Secret Scanning (Gitleaks) ----------
  gitleaks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}  
        with:
          args: detect --source=. --verbose --redact --exit-code=1

  # ---------- 4. OWASP Dependency Check ----------
  dependency-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "YourProject"
          path: "./"
          format: "HTML"
          out: "reports"

      - name: Upload OWASP Dependency Check Report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: reports


          